/**/
test({
    "count": 50100,
    "results": [{
        "listing_id": 197408149,
        "state": "active",
        "user_id": 40219264,
        "category_id": 68899488,
        "title": "Hand stamped vintage gold spoon, Gold flatware, Stamped spoon, Anniversary gift idea, Custom silverware, Stamped gold,",
        "description": "What a sweet spoon this is.. and ready to ship too!  You will receive the exact spoon as shown in the photos.\r\n\r\nThis listing is for a never used gold plated spoon that has been hand stamped, one letter at a time, to say &quot;I love you&quot;.   It is shiny and adorable, sure to bring a smile to anyone&#39;s face.  This spoon is a thoughtful gift to warm the heart of someone you love.\r\n\r\nYour spoon will be wrapped in tissue and a bow (ribbon colors vary) ready for gift giving.  If you are sending this directly as a gift, please let me know as I would be happy to add a short note card from you.\r\n\r\n          ~Please read before completing your purchase~\r\n\r\nHand stamping is much different that engraving, both in process and appearance. Hand stamping is done by hammering the letters, one at a time, using a hammer and metal tools. Because it is created by a person, and not a machine, there no two pieces will ever be alike. There will always be differences in letter spacing, alignment and letter depth. The letters will not line up perfectly. This is to be expected with this process and not a defect in any way. Some tool marks can sometimes be seen on the back and\/or the front of the item. Hand stamping creates one of a kind perfect imperfections\u2026. A look that is made by a person and not a machine.\r\n\r\nHand washing is recommended to protect your flatware. Darkening of the letters will fade depending on frequency of use and how it is cleaned. The stamping of the letters is deep and will be there always.",
        "creation_tsz": 1422984684,
        "ending_tsz": 1433349084,
        "original_creation_tsz": 1406133766,
        "last_modified_tsz": 1422984684,
        "price": "14.00",
        "currency_code": "USD",
        "quantity": 1,
        "tags": ["hand stamped", "silverware", "gold", "gold silverware", "hand stamped spoon", "custom silverware", "gold spoon", "stamped spoon", "stamped utiinsil", "hammered spoon", "vintage gold spoon", "anniversary gift", "gold flatware"],
        "category_path": ["Housewares", "Kitchen", "Utensil"],
        "category_path_ids": [69150425, 68891062, 68899488],
        "materials": ["gold plated spoon", "vintage"],
        "shop_section_id": 15903619,
        "featured_rank": null,
        "state_tsz": 1421406615,
        "url": "https:\/\/www.etsy.com\/listing\/197408149\/hand-stamped-vintage-gold-spoon-gold?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 178,
        "num_favorers": 23,
        "shipping_template_id": 7385605744,
        "processing_min": 3,
        "processing_max": 5,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 150488645,
        "state": "active",
        "user_id": 8767034,
        "category_id": 68898570,
        "title": "Blue Green Earrings, Glass Art Earrings, Lampwork Earrings, Glass Bead Earrings, Beadwork Earrings, Unique Earrings, Abstract Earrings",
        "description": "Handcrafted earrings with SRA artisan crafted lampwork glass beads, Swarovski Crystal, and sterling silver.\r\n\r\nThese amazing earrings are made with 22mm free-form SRA lampwork glass beads made by an amazing glass artist. They have a turquoise blue base encased in transparent teal blue glass with green swirls and goldstone twirls. They are finished off with lime green glass dots. \r\n\r\nI have paired them with Blue Zircon AB2X and Peridot AB2X Swarovski Crystal creating a beautiful color combination while keeping the design simple and focused on the beads themselves. Sterling silver bead caps and beads complete the look and add brilliance.\r\n\r\nThey suspend from sterling silver ear wires and measure 2 inches (5.08cm) from the top arch of ear wire.",
        "creation_tsz": 1422984682,
        "ending_tsz": 1433349082,
        "original_creation_tsz": 1367892836,
        "last_modified_tsz": 1422984682,
        "price": "44.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["Lampwork Earrings", "Colorful Earrings", "Lampwork Jewelry", "Abstract Earrings", "Beadzandmore", "Glass Bead Earirngs", "Beaded Earrings", "Beadwork Earrings", "Glass Beads Earrings", "Glass Bead Jewelry", "Blue Green Earrings", "Unique Earrings", "Glass Art Earrings"],
        "category_path": ["Jewelry", "Earrings", "Glass"],
        "category_path_ids": [68887482, 69151501, 68898570],
        "materials": ["sra lampwork glass beads", "sterling silver", "Swarovski Crystal"],
        "shop_section_id": 7687582,
        "featured_rank": null,
        "state_tsz": 1367892836,
        "url": "https:\/\/www.etsy.com\/listing\/150488645\/blue-green-earrings-glass-art-earrings?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 146,
        "num_favorers": 27,
        "shipping_template_id": 7827091,
        "processing_min": 1,
        "processing_max": 1,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": "women",
        "occasion": null,
        "style": ["Abstract"],
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 191037429,
        "state": "active",
        "user_id": 14652504,
        "category_id": 68892168,
        "title": "Wedding Table Sign - Custom Last Name for sweetheart table",
        "description": "----------------------------------------------------\r\n****IMPORTANT ANNOUNCEMENT****\r\n----------------------------------------------------\r\nTo my lovely customers:\r\nThe very fastest way to get answers to your questions is to **read this entire listing**. If you message me, please know that it is currently peak season and I am managing a heavy volume of orders + inquiries and will respond as quickly as I can--but it may take me a few days. I am a one woman business and am busy day and night hand crafting the one of a kind decor you see here. \r\n\r\n::: CURRENT LEAD TIME :::\r\nThis item will ship in **2 weeks**. I am not accepting rush orders at this time, so sorry!\r\n\r\n::: SHIPPING INFO :::\r\nUS orders: 2 - 3 business days via USPS Priority Mail\r\n\r\nInternational orders*: about 10 business days (2 weeks) via USPS First Class Mail (no tracking)\r\n*Faster shipping + tracking available for int&#39;l orders available for an extra fee under the &quot;Shipping Options&quot; drop down menu at checkout. \r\n\r\nInternational buyers: I happily ship all over the world. Please see my shop policies before purchasing:\r\nhttp:\/\/www.etsy.com\/shop\/betteroffwed\/policy\r\n\r\n::: HELLO! ::: \r\nI\u2019m Tina, the designer behind Better Off Wed. \r\n\r\nEach piece of artisan wedding decor is lovingly-crafted by me in the heart of Austin, TX. \r\n\r\n ::: TOP SHELF MATERIALS :::\r\nYour table sign is made from the highest quality materials available. I work with a sturdy and eco-friendly wood board made from recycled eucalyptus tree fibers. \r\n\r\n ::: WHAT YOU GET :::\r\nOne freestanding custom table sign with your future last name! The lettering of the sign is 14.5&quot; wide and about 7&quot; tall. The total height from the base of the sign to the top is 10&quot;. It&#39;s shown next to jumbo sized cupcakes and two mini champagne bottles to help you understand its relative size. \r\n\r\nLooking for a different phrase or size? I can make just about anything! Just send me a convo letting me know what you&#39;re looking for :) \r\n\r\n::: MADE JUST FOR YOU :::\r\nEach sign is completely original + one-of-a-kind. No mass production. Just pure love + care. \r\n\r\n::: BEST CUSTOMER SERVICE ON THE INTERNET ::: \r\nOr so they tell me ;) I live for the thrill of making my customers happy and will make sure you\u2019re 100% ecstatic about your order. Pinky swear.  \r\n\r\n::: HOW TO ORDER :::\r\nA. Please select your lettering color choice from the drop down menu.\r\n\r\nB. During checkout, in the MESSAGE to SELLER box, please include:\r\n\r\n\u2022 The bride and groom&#39;s last name &lt;3 I&#39;m happy to make this topper with any length last name. Please note that if your last name is longer than 8 letters I will need to make your topper slightly wider--up to 9&quot;. \r\n\r\n\u2022 The couple&#39;s wedding date, or the date the order must be received\r\n\r\n::: AS FEATURED IN :::\r\nMartha Stewart Weddings Magazine, Style Me Pretty, Etsy Featured Seller, Bridal Guide, 100 Layer Cake, Wedding Bee, Emmaline Bride, Brides.com, Green Weddings Shoes, One Wed, Broke Ass Bride, Wedding Chicks and more. \r\n\r\n::: MORE GORGEOUS WEDDING DECOR :::\r\nCan be found here: http:\/\/www.etsy.com\/shop\/betteroffwed\r\n\r\n\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\r\n\r\nRave Reviews:\r\n\r\n\u201cIt is just so amazing &lt;3. i keep opening the box to take a peak at it cause i dont get to use it for a little while. but once i&#39;ve used it, it will be getting framed. Fantastic buy and great service !!!\u201d\r\n\r\n- Courtney\r\n\r\n\u201cIf I could give this fifty positives I would because that&#39;s just how much in love I am with this! I cannot wait to see it on my wedding cake. Fast shipping. Thanks so much!\u201d\r\n\r\n- Brittany\r\n\r\n\u201cI couldn&#39;t love this cake topper any more if I tried - it is beyond PERFECT!! It is so much more than I expected ... just beautiful, wonderful work. Beyond that, I would love to do business again with this merchant ... quick responses, constant follow-up ... definitely someone who goes above and beyond to make sure her customers are happy. Great experience!!!\u201d\r\n\r\n- Heather\r\n\r\n\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8\u00b0\u00ba*:\u2022.-:\u00a6:-\u2022*\u00ba\u00b0\u00a8\u00a8",
        "creation_tsz": 1422984682,
        "ending_tsz": 1433349082,
        "original_creation_tsz": 1401235920,
        "last_modified_tsz": 1422984682,
        "price": "115.00",
        "currency_code": "USD",
        "quantity": 70,
        "tags": ["wedding", "wedding decor", "wedding accessories", "better off wed", "photo prop", "betteroffwed", "wedding sign", "mr and mrs", "mr and mrs sign", "table sign", "custom table sign", "sweetheart table", "wedding table sign"],
        "category_path": ["Weddings", "Cake Topper"],
        "category_path_ids": [68887494, 68892168],
        "materials": ["recycled eucalyptus fiber board", "paint", "birch", "mahogany"],
        "shop_section_id": 15470064,
        "featured_rank": null,
        "state_tsz": 1413278543,
        "url": "https:\/\/www.etsy.com\/listing\/191037429\/wedding-table-sign-custom-last-name-for?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 1595,
        "num_favorers": 116,
        "shipping_template_id": null,
        "processing_min": 10,
        "processing_max": 10,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": "wedding",
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 207068717,
        "state": "active",
        "user_id": 10712618,
        "category_id": 69172099,
        "title": "KNIT Jersey ORGANIC Fabric Certified Cotton, Birch fabric, Peonies Blue Knit textile from Acorn Trail knits collection, Baby kids",
        "description": "Organic Cotton knit prints, Acorn Trail knits collection from Birch Fabrics, fabric sold by the Fat Quarter, 1\/2 yard or more.\r\n\r\nThe Acorn Trail Knit collection is 100% GOTS-certified organic, ensuring that it is produced in an environmentally and socially sustainable manner. \r\nFabric is 44-45&quot; in width.\r\n\r\n---------------------------------\r\nChoose fabric Size and Quantity in the drop-down menu when adding to your cart.\r\n\r\nFABRIC WILL BE CUT AS ONE CONTINUOUS PIECE WITH MULTIPLE FAT QUARTER OR HALF\/YARD QUANTITIES.\r\n----------------------------------\r\n\r\n*  Fat Quarter (approximately 18&quot; x 22&quot; including selvages)\r\nYardage is cut in one final piece.\r\n\r\n*  Half- Yard cut is approximately 18&quot; x 44\/45&quot; including selvages.\r\nIf you would like to purchase 1 Yard, you would enter 2 in the Qty. box at Checkout. Yardage is cut in one continuous piece.\r\nFor example:\r\n1\/2 yard = 1 Qty\r\n1 yard = 2 Qty\r\n1 1\/2 yard = 3 Qty\r\n2 yards = 4 Qty    \r\nYardage is cut in one final piece.\r\n\r\n***All fabrics are available as yardage, half yards, fat quarters, etc. I welcome custom cuts. If you don&#39;t find exactly what you&#39;re looking for please send me a convo. I&#39;d be happy to make a custom order for you!\r\n\r\n*** Please check the &quot;Announcement&quot;on the main page of my shop for current turnaround time and discounts. http:\/\/www.etsy.com\/shop\/daisiescrochet?ref=seller_info\r\n\r\n*** Note: Colors may vary slightly due to current yarn dye lots, computer monitor projections and photo lighting.\r\nSwatches\/Supplies: https:\/\/www.etsy.com\/shop\/daisiescrochet?section_id=10239275&ref=shopsection_leftnav_4\r\nOrganic Fabric: https:\/\/www.etsy.com\/shop\/daisiescrochet?section_id=14701824&ref=shopsection_leftnav_1\r\nDesigner Fabric: https:\/\/www.etsy.com\/shop\/AACottonCreations?section_id=14898942&ref=shopsection_leftnav_3\r\nFabric Bundles: https:\/\/www.etsy.com\/shop\/AACottonCreations?section_id=10239257&ref=shopsection_leftnav_4",
        "creation_tsz": 1422984682,
        "ending_tsz": 1433349082,
        "original_creation_tsz": 1413251657,
        "last_modified_tsz": 1422984682,
        "price": "4.30",
        "currency_code": "USD",
        "quantity": 20,
        "tags": ["Organic Cotton", "Organic Fabric", "bedding baby fabric", "cloths fabric", "half yard fat quater", "eco friendly", "gots fabric", "fabric for clothing", "knit  organic fabric", "birch fabrics", "children fabric", "modern textile", "Girl print fabric"],
        "category_path": ["Supplies", "Fabric", "Cotton"],
        "category_path_ids": [69150433, 68888310, 69172099],
        "materials": ["organic cotton fabric", "knit textile"],
        "shop_section_id": 10239275,
        "featured_rank": null,
        "state_tsz": 1414754213,
        "url": "https:\/\/www.etsy.com\/listing\/207068717\/knit-jersey-organic-fabric-certified?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 524,
        "num_favorers": 117,
        "shipping_template_id": 4921546524,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "someone_else",
        "is_supply": "true",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 167130173,
        "state": "active",
        "user_id": 23931806,
        "category_id": 68891034,
        "title": "Rolling Stones Band Vinyl Record 7 inch 45 rpm Mick Jagger Keith Richards She&#39;s a Rainbow 2000 Light Years From Home 1967 Psychedelic Rock",
        "description": "The Rolling Stones - She&#39;s A Rainbow - domestic 7&quot; single  - 1967    FREE within the USA Shipping, Insurance & Tracking\r\n\r\nThis is a 45 rpm vinyl record single for The Rolling Stones and is almost 50 years old!  It is from 1967 and features She&#39;s A Rainbow, and the b-side is 2,000 Light Years From Home, which were from the LP Their Satanic Majesties Request.  It is in good condition with just some light surface wear from when we had it in our jukebox.  It is guaranteed to play fine and 100% guaranteed to meet your satisfaction....even though Mick can&#39;t get no satisfaction :)  \r\n\r\nWe have been collecting vintage clothing and objects for years and owned two Mohawk Music record stores and are now letting some of collection go on Etsy --- check out our shops! \r\n\r\nhttp:\/\/www.etsy.com\/shop\/plattermatter --- for vintage clothing and accessories\r\n\r\nhttps:\/\/www.etsy.com\/shop\/MohawkMusic --- for vintage T-shirts, pinbacks music collectibles and vinyl \/ cds\r\n\r\nhttp:\/\/www.etsy.com\/shop\/plattermatter2 ---- for vintage home, tiki, ephemera and sewing\r\nMohawk Music was the partnership of George from Rainbow Records in OKC and Norman and Paul from Starship in Tulsa.  We originally opened Mohawk Music in Tulsa in 1988 and in Dallas in 1992.  We have decided to continue the tradition of selling our personal collections as we did back in 1988 when our first store opened.  So be sure to check out our shop from time to time as we uncover relics from the past.  We guarantee our items and strive for 100 percent satisfaction from our clients.",
        "creation_tsz": 1422984677,
        "ending_tsz": 1433349077,
        "original_creation_tsz": 1382886464,
        "last_modified_tsz": 1422984677,
        "price": "24.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["single", "record", "7 inch", "music", "vinyl", "45 rpm", "rolling stones", "keith richards", "mick jagger", "shes a rainbow", "brian jones", "bill wyman", "psychedelic"],
        "category_path": ["Vintage", "Collectibles"],
        "category_path_ids": [69150437, 68891034],
        "materials": ["vinyl record", "single", "Free usa shipping", "7 inch 45 rpm"],
        "shop_section_id": 12745083,
        "featured_rank": null,
        "state_tsz": 1412603245,
        "url": "https:\/\/www.etsy.com\/listing\/167130173\/rolling-stones-band-vinyl-record-7-inch?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 67,
        "num_favorers": 5,
        "shipping_template_id": 3609427408,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "someone_else",
        "is_supply": "false",
        "when_made": "1960s",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": ["Rocker", "Hipster"],
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 186456933,
        "state": "active",
        "user_id": 33298965,
        "category_id": 68905810,
        "title": "Vintage 1965 Simplicity Womens Shorts and Pants Sewing Pattern No. 5973, Miss Sz, Waist 25, Hip 34",
        "description": "Has been cut.  All pieces remain intact and in excellent condition.  Envelope shows wear, tears and the back flap has been removed.",
        "creation_tsz": 1422984675,
        "ending_tsz": 1433349075,
        "original_creation_tsz": 1397686420,
        "last_modified_tsz": 1422984675,
        "price": "5.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["vintage", "patterns", "sewing patterns", "patterns to sew", "women", "clothing", "pants pattern", "shorts pattern", "simplicity", "simplicity patterns", "simplicity 5973 5973", "supplies", "vintage patterns"],
        "category_path": ["Vintage", "Clothing", "Women"],
        "category_path_ids": [69150437, 69154945, 68905810],
        "materials": ["paper"],
        "shop_section_id": 13619584,
        "featured_rank": null,
        "state_tsz": 1419344427,
        "url": "https:\/\/www.etsy.com\/listing\/186456933\/vintage-1965-simplicity-womens-shorts?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 24,
        "num_favorers": 0,
        "shipping_template_id": null,
        "processing_min": 1,
        "processing_max": 3,
        "who_made": "someone_else",
        "is_supply": "false",
        "when_made": "before_1996",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 186459413,
        "state": "active",
        "user_id": 33298965,
        "category_id": 68905810,
        "title": "Vintage 1966 Simplicity Womens Dress Sewing Pattern No. 6539, Miss Sz 12",
        "description": "Has been cut.  Suitable for sheer fabrics.  All pieces and instructions are intact and in excellent condition.  The envelope shows some wear, tears and wrinkles.",
        "creation_tsz": 1422984675,
        "ending_tsz": 1433349075,
        "original_creation_tsz": 1397687766,
        "last_modified_tsz": 1422984675,
        "price": "5.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["vintage", "patterns", "vintage patterns", "sewing patterns", "patterns to sew", "women", "clothing", "dress pattern", "simplicity", "simplicity patterns", "simplicity 6539", "6539", "supplies"],
        "category_path": ["Vintage", "Clothing", "Women"],
        "category_path_ids": [69150437, 69154945, 68905810],
        "materials": ["paper"],
        "shop_section_id": null,
        "featured_rank": null,
        "state_tsz": 1419344427,
        "url": "https:\/\/www.etsy.com\/listing\/186459413\/vintage-1966-simplicity-womens-dress?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 31,
        "num_favorers": 1,
        "shipping_template_id": null,
        "processing_min": 1,
        "processing_max": 3,
        "who_made": "someone_else",
        "is_supply": "false",
        "when_made": "1960s",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 172831861,
        "state": "active",
        "user_id": 33298965,
        "category_id": 68905810,
        "title": "Vintage Vogue Paris Original Womens Dress Sewing Pattern No. 1375, Sz 12, Emanuel Ungaro",
        "description": "Has been used.  All pieces and instructions intact and in excellent condition. The envelope at the back has been torn and a portion is missing.  The sizing measurement chart remains unharmed.",
        "creation_tsz": 1422984674,
        "ending_tsz": 1433349074,
        "original_creation_tsz": 1386913970,
        "last_modified_tsz": 1422984674,
        "price": "5.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["vintage", "patterns", "vintage patterns", "patterns to sew", "dress pattern", "vogue", "vogue patterns", "paris original", "women", "clothing", "Vogue 1375", "sewing patterns", "supplies"],
        "category_path": ["Vintage", "Clothing", "Women"],
        "category_path_ids": [69150437, 69154945, 68905810],
        "materials": [],
        "shop_section_id": 13619584,
        "featured_rank": null,
        "state_tsz": 1419344428,
        "url": "https:\/\/www.etsy.com\/listing\/172831861\/vintage-vogue-paris-original-womens?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 95,
        "num_favorers": 3,
        "shipping_template_id": null,
        "processing_min": 1,
        "processing_max": 3,
        "who_made": "someone_else",
        "is_supply": "false",
        "when_made": "before_1996",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 172831125,
        "state": "active",
        "user_id": 33298965,
        "category_id": 68905810,
        "title": "Vintage Vogue Womens Paris Original Dress Sewing Pattern No. 2352, Sz 10, Nina Ricci",
        "description": "Has been used.  All pieces and instructions remain intact and in excellent condition.  The shortened version of the dress has been cut, however, the cut off portion remains in the envelope.  The envelope is in very good to excellent condition.",
        "creation_tsz": 1422984674,
        "ending_tsz": 1433349074,
        "original_creation_tsz": 1386913196,
        "last_modified_tsz": 1422984674,
        "price": "5.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["vintage", "patterns", "vintage patterns", "sewing patterns", "women", "clothing", "dress pattern", "vogue", "vogue patterns", "vogue paris original", "vogue 2352", "supplies", "patterns to sew"],
        "category_path": ["Vintage", "Clothing", "Women"],
        "category_path_ids": [69150437, 69154945, 68905810],
        "materials": ["paper"],
        "shop_section_id": 13619584,
        "featured_rank": null,
        "state_tsz": 1419344428,
        "url": "https:\/\/www.etsy.com\/listing\/172831125\/vintage-vogue-womens-paris-original?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 49,
        "num_favorers": 0,
        "shipping_template_id": null,
        "processing_min": 1,
        "processing_max": 3,
        "who_made": "someone_else",
        "is_supply": "false",
        "when_made": "before_1996",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 221199661,
        "state": "active",
        "user_id": 49680659,
        "category_id": 68933706,
        "title": "Black polka dot garter set Bridal garter set Luxury lingerie Pure black silk garter Wedding garter minimalist lingerie Designer Lingerie",
        "description": "Mocha Charmeuse 100 % silk + polka dot tulle garter set of 2 in gift box.\r\n\r\nGARTER WIDTH - 6 cm \/ 2,3&quot; ( silk appr. 2cm \/ 0,8&quot; and tulle 4cm \/ 1,5&quot; )\r\n\r\nSIZE\r\nMy standard size stretches from 41 cm - 55 cm \/ 16 - 22\u201d. \r\nIf you need a smaller or larger size, please choose &quot;other&quot; in options and note your leg measurement when you place your order.\r\n\r\nVarious colors available\r\n\u25cf Black silk and black polka dot tulle\r\n\u25cf Natural white silk and natural white polka dot tulle\r\n\r\n\u25cf Peach silk and black polka dot tulle\r\n\u25cf Peach silk and natural white polka dot tulle\r\n\r\n\u25cf Mocha silk and black polka dot tulle\r\n\u25cf Mocha silk and natural white polka dot tulle\r\n\r\nOriginal design by Teverani OptimImpera Lingerie,\r\nitem is labeled and arrives in an elegant gift box.\r\n\r\nThis item is hand made from delicate fabrics by using haute couture sewing techniques\r\nFor right care- gentle hand wash warm water, no tumble try \r\n\r\n\r\nItem is ready to ship in 6- 14 days. All packages will be sent registred and with tracking code!\r\nWe ship items from Estonia, Europe by using Estonian Post. \r\nWe ship FREE and WORLDWIDE.\r\n\r\nPayment is expected at the time of purchase. Orders are not shipped until payment is complete. Made to order items are not started until payment is complete. Unpaid orders will be cancelled within 2 days if I don&#39;t receive an e-mail from you to discuss a possible problem.\r\n\r\nIf you wish this made in other size, other color, with a bit different design etc. let us know and we do all we can to make you happy",
        "creation_tsz": 1422984672,
        "ending_tsz": 1433349072,
        "original_creation_tsz": 1422984672,
        "last_modified_tsz": 1422984672,
        "price": "64.00",
        "currency_code": "EUR",
        "quantity": 1,
        "tags": ["luxury lingerie", "black polka dot", "polka dot lingerie", "black silk garter", "silk garter set", "black garter set", "silk lingerie", "minimalist lingerie", "luxury wedding", "black bridal garter", "nude lingerie", "beige garter set", "nude garter set"],
        "category_path": ["Clothing", "Lingerie", "Garter"],
        "category_path_ids": [69150353, 69153081, 68933706],
        "materials": ["Soft tulle", "Charmeuse silk"],
        "shop_section_id": 16439991,
        "featured_rank": null,
        "state_tsz": 1422984672,
        "url": "https:\/\/www.etsy.com\/listing\/221199661\/black-polka-dot-garter-set-bridal-garter?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 0,
        "num_favorers": 0,
        "shipping_template_id": null,
        "processing_min": 5,
        "processing_max": 10,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": "women",
        "occasion": "valentines",
        "style": ["High Fashion", "Avant Garde"],
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 130650397,
        "state": "active",
        "user_id": 23637444,
        "category_id": 68919936,
        "title": "Organic Vanilla Perfume Oil \/ Barrel Aged Vanilla \/ Bourbon Vanilla \/ Vanilla Oil \/ Natural Perfume",
        "description": "VANILLA BEAN PERFUME OIL  - .5 fl oz (15ml)\r\n\r\n100% Pure  \u2022  Organic  \u2022  All Natural  \u2022  Unrefined\r\n\r\nWe create our signature fragrance by hand in small batches using a special process that we developed combining pure organic unrefined jojoba oil with the highest quality whole organic vanilla beans from Madagascar and naturally age them for months with charred oak bourbon barrel staves.  This unique process yields a light but complex and smokey vanilla fragrance that can only be achieved by us with time and great patience.\r\n\r\nThis is NOT an artificial fragrance concentrate.  Most vanilla-scented products contain artificial fragrance concentrates because they&#39;re very strong, inexpensive and easy to source.  Unfortunately, artificial fragrance concentrates also use harsh chemicals to achieve their synthetic &quot;vanilla-like&quot; scent.  Due to their widespread use, these artificial concentrates have become confused with the scent of real vanilla and unfortunately, many people have now come to expect the scent of artificial vanilla concentrates, which are cloyingly sweet with an overwhelming aroma.  Our vanilla perfume oil is not like these arificial fragrance concentrates - it is a light and subtle fragrance that is completely natural with just two ingredients - organic oil and vanilla beans.  Nature&#39;s Best - Pure & Simple.\r\n\r\nCAP TYPE:\r\nOur Vanilla Bean Perfume automatically comes with a PLAIN cap but if you&#39;d prefer a ROLL-ON cap instead, just add a Note to Seller during checkout.\r\n\r\nINGREDIENTS:\r\nCertified Organic Jojoba Oil\r\nCertified Organic Vanilla Beans\r\n\r\nDIRECTIONS:\r\nApply small amount to skin and rub until absorbed.\r\n \r\nPRECAUTIONS:\r\nFor external use only. Avoid contact with eyes.  Keep out of reach of children. Secure cap firmly.  Always store in a cool, dark location.  Estimated shelf-life is up to one year under ideal storage conditions.\r\n \r\nHandcrafted in East Grand Rapids, Michigan, U.S.A.\r\n\r\n*Read all individual listings and shop policies thoroughly prior to purchasing.  By purchasing fr\u00e5n kr\u00e4mer\u00ae products, you express understanding of and agreement with all terms outlined in this listing and all other terms and policies outlined elsewhere in this seller&#39;s shop.",
        "creation_tsz": 1422984672,
        "ending_tsz": 1433349072,
        "original_creation_tsz": 1367448403,
        "last_modified_tsz": 1422984672,
        "price": "25.00",
        "currency_code": "USD",
        "quantity": 6,
        "tags": ["Fall", "Autumn", "vanilla", "jojoba", "perfume", "aged vanilla", "vanilla bean", "perfume oil", "organic perfume", "natural perfume", "vanilla perfume", "vanilla oil", "bourbon vanilla"],
        "category_path": ["Bath and Beauty", "Fragrance", "Oil"],
        "category_path_ids": [68887336, 69152437, 68919936],
        "materials": ["Organic Jojoba oil", "Organic vanilla bean"],
        "shop_section_id": null,
        "featured_rank": null,
        "state_tsz": 1422182082,
        "url": "https:\/\/www.etsy.com\/listing\/130650397\/organic-vanilla-perfume-oil-barrel-aged?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 7183,
        "num_favorers": 922,
        "shipping_template_id": null,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 96863509,
        "state": "active",
        "user_id": 14187503,
        "category_id": 69169877,
        "title": "Big Brass Oyster Shell",
        "description": "This listing is for one really large brass oyster shell. Beautiful and fit for a Botticelli maiden! It would be gorgeous with a verdigris finish, or use its exquisite form as a pottery mold. I just love this one for its old school style and elegance. Ring attached for easy hanging.\r\n\r\n 2 3\/4&quot; tall - ring optional. \r\n\r\nRaw Yellow Brass\r\n\r\nHollow back",
        "creation_tsz": 1422984668,
        "ending_tsz": 1433349068,
        "original_creation_tsz": 1333579882,
        "last_modified_tsz": 1422984668,
        "price": "7.00",
        "currency_code": "USD",
        "quantity": 9,
        "tags": ["shell", "sea", "beach", "ocean", "resort", "vacation", "frame", "theme", "scrapbook", "shadow box", "mermaid", "aquatic", "fantasy"],
        "category_path": ["Vintage", "Supplies", "Charm"],
        "category_path_ids": [69150437, 69153885, 69169877],
        "materials": ["brass", "metal", "die", "stamping", "copper"],
        "shop_section_id": 12880475,
        "featured_rank": null,
        "state_tsz": 1414348835,
        "url": "https:\/\/www.etsy.com\/listing\/96863509\/big-brass-oyster-shell?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 380,
        "num_favorers": 63,
        "shipping_template_id": null,
        "processing_min": null,
        "processing_max": null,
        "who_made": "someone_else",
        "is_supply": "true",
        "when_made": "before_1996",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": ["Art Nouveau", "Mediterranean"],
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 207872989,
        "state": "active",
        "user_id": 32508243,
        "category_id": 69150467,
        "title": "Happy face camera lens cap and leash combo for Canon, Nikon, Fuji, Sony etc. DSLR, mirrorless cameras. Free shipping in North America.",
        "description": "Quality custom lens caps and leashes from MyLensCap add style and flair to your camera.  This happy face lens cap\/leash design offers an attractive and practical accessory for your photography.\r\n\r\nWe use quality inks printed on durable vinyl, finished with a glossy laminate.  Images are permanently affixed to lens caps\/leashes designed to fit safely and securely to your camera.\r\n\r\n****NOTE: When attaching your leash to your lens cap be sure to get placement correct because once the sticky side is placed on the lens cap it is virtually impossible to pull it off.\r\n\r\nOrders are shipped out in 1-2 business days through the post office.\r\n\r\nNorth American orders typically will arrive within 3-14 business days.\r\n\r\nInternational orders typically will arrive within 2-6 weeks.",
        "creation_tsz": 1422984668,
        "ending_tsz": 1433349068,
        "original_creation_tsz": 1413828108,
        "last_modified_tsz": 1422984668,
        "price": "16.99",
        "currency_code": "CAD",
        "quantity": "1",
        "tags": ["camera strap", "photo accessory", "dslr camera", "photography gift", "personalized cap", "strap cover", "camera case", "custom lens caps", "lens cap holder", "lens cover", "photographer print", "lens cap leash"],
        "category_path": ["Accessories"],
        "category_path_ids": [69150467],
        "materials": [],
        "shop_section_id": 16200010,
        "featured_rank": null,
        "state_tsz": 1413828162,
        "url": "https:\/\/www.etsy.com\/listing\/207872989\/happy-face-camera-lens-cap-and-leash?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 5,
        "num_favorers": 0,
        "shipping_template_id": 4024755547,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 221199653,
        "state": "active",
        "user_id": 5754444,
        "category_id": 69169615,
        "title": "Customized Wedding Invitation Printable Wedding Invitations Design T010VN",
        "description": "Design T010VN\r\n\r\nThis listing is for digital files that I customize for you and then you may print the files at home or at a print lab\/shop. This beautiful wedding invitation fits perfectly in a #10 envelope. Measures 4x9 inches. Comes in jpg and pdf file formats for easy printing!\r\n\r\nI can also create coordinating engagement party, rehearsal dinner, and bridal shower invitations as well as coordinating wedding programs, place cards, buffet signs, wedding signs, posters, etc. \r\nINTERNATIONAL CUSTOMERS: Yes! I can create cards in the language of your choice as long as you provide the translation. \r\n\r\n----------{PRICE LIST}----------\r\n$12.00 for invitations \r\n$25.00 for invitations with coordinating information cards\r\n\r\nPlease convo if you have any questions or special requests before purchasing.\r\n\r\n-----------{TIME FRAME & REVISIONS}-----------\r\nAfter you purchase, the design work can begin and you will receive proofs within 72 hours (3-5 days if you need a custom color palette). No limit to text revisions, I want the wording to be exactly what you want. Heavy revisions can take up to 48 hours to accommodate. \r\n\r\n----------{ADDITIONAL FEES}------------\r\nAfter final files are sent, I accommodate every reasonable \u201cquick change\/edit\u201d request without charging extra, unfortunately some requests that are made AFTER proofs or final files are sent will require an additional fee. \r\n\r\nSome examples: A complete design change after proofs are sent. Resizing files or adding bleeds AFTER FINAL files are sent will also incur extra charges.\r\n\r\n\r\n----------{INFORMATION}------------\r\n\r\nYou may copy and paste the following into a convo or you may add your details in the &quot;notes to seller&quot; box when purchasing.\r\n\r\n***INVITATION***\r\n\u2022Couples names (please type names in the order you wish for them to appear):\r\n\u2022Wedding Date:\r\n\u2022Wedding Time:\r\n\u2022Wedding location (venue, street address, city, state, zip):\r\n\u2022Text to add\/delete\/change from invite:\r\n\r\n***RSVP***\r\nRSVP by Date:\r\nEntrees (if applicable):\r\n\u2022Text to add\/delete\/change from RSVP:\r\n\r\n***RECEPTION****\r\nPlease enter text to all the applies\r\n\u2022venue name:\r\n\u2022venue address (street, city, state, zip):\r\n\u2022time\r\n\u2022additional text to include on card\r\n\r\n***ACCOMMODATIONS****\r\nPlease enter text to all the apply\r\n\u2022hotel name:\r\n\u2022hotel address (street, city, state, zip):\r\n\u2022hotel phone:\r\n\u2022group code\r\n\u2022 additional text to include on card\r\n\r\n***RSVP***\r\nRSVP by Date:\r\nEntrees (if applicable):\r\n\u2022Text to add\/delete\/change from RSVP:",
        "creation_tsz": 1422984668,
        "ending_tsz": 1433349068,
        "original_creation_tsz": 1422984668,
        "last_modified_tsz": 1422984668,
        "price": "12.00",
        "currency_code": "USD",
        "quantity": 1,
        "tags": ["invitation printable", "wedding printables", "printable wedding", "diy invitation", "invitation suite", "country wedding", "rustic wedding", "retro wedding", "wedding trends", "popular wedding", "popular printables", "wedding favors", "black and white"],
        "category_path": ["Weddings", "Card", "Invitation"],
        "category_path_ids": [68887494, 68892174, 69169615],
        "materials": [],
        "shop_section_id": 15607289,
        "featured_rank": null,
        "state_tsz": 1422984668,
        "url": "https:\/\/www.etsy.com\/listing\/221199653\/customized-wedding-invitation-printable?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 0,
        "num_favorers": 0,
        "shipping_template_id": 2610809965,
        "processing_min": 1,
        "processing_max": 3,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 214144829,
        "state": "active",
        "user_id": 55629791,
        "category_id": 69171729,
        "title": "Jack Skellington Skeleton on Cotton Jersey Fabric inspired by Nightmare Before Christmas [SKU:MFR2FAB001]",
        "description": "Content: 100% Cotton Jersey\r\nWidth: 60&quot;\r\nWeight: 10 oz\r\nGreat Quality!\r\n\r\nQuantity is in 1 yard increments.  Multiple quantities ordered will be continuous yardage.\r\nThis is shipped out directly from our supplier, via USPS First Class Mail or Priority Mail.",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1417802953,
        "last_modified_tsz": 1422984667,
        "price": "8.00",
        "currency_code": "USD",
        "quantity": 30,
        "tags": ["fabric", "knit", "cotton", "jersey", "jack", "skellington", "skeleton", "white", "black", "red", "pink", "nightmare", "before christmas"],
        "category_path": ["Supplies", "Fabric", "Yardage"],
        "category_path_ids": [69150433, 68888310, 69171729],
        "materials": ["cotton"],
        "shop_section_id": 16279103,
        "featured_rank": 6,
        "state_tsz": 1422960918,
        "url": "https:\/\/www.etsy.com\/listing\/214144829\/jack-skellington-skeleton-on-cotton?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 879,
        "num_favorers": 75,
        "shipping_template_id": 8817778570,
        "processing_min": 3,
        "processing_max": 5,
        "who_made": "someone_else",
        "is_supply": "true",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 207873429,
        "state": "active",
        "user_id": 32508243,
        "category_id": 69150467,
        "title": "Paw print camera lens cap and leash combo for Canon, Nikon, Fuji, Sony etc. DSLR, mirrorless cameras. Free shipping in North America.",
        "description": "Quality custom lens caps and leashes from MyLensCap add style and flair to your camera.  This paw print lens cap\/leash design offers an attractive and practical accessory for your photography.\r\n\r\nWe use quality inks printed on durable vinyl, finished with a glossy laminate.  Images are permanently affixed to lens caps\/leashes designed to fit safely and securely to your camera.\r\n\r\n****NOTE: When attaching your leash to your lens cap be sure to get placement correct because once the sticky side is placed on the lens cap it is virtually impossible to pull it off.\r\n\r\nOrders are shipped out in 1-2 business days through the post office.\r\n\r\nNorth American orders typically will arrive within 3-14 business days.\r\n\r\nInternational orders typically will arrive within 2-6 weeks.",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1413828324,
        "last_modified_tsz": 1422984667,
        "price": "16.99",
        "currency_code": "CAD",
        "quantity": "1",
        "tags": ["camera strap", "photo accessory", "dslr camera", "photography gift", "personalized cap", "strap cover", "camera case", "custom lens caps", "lens cap holder", "lens cover", "photographer print", "lens cap leash"],
        "category_path": ["Accessories"],
        "category_path_ids": [69150467],
        "materials": [],
        "shop_section_id": 16200010,
        "featured_rank": null,
        "state_tsz": 1413828324,
        "url": "https:\/\/www.etsy.com\/listing\/207873429\/paw-print-camera-lens-cap-and-leash?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 10,
        "num_favorers": 0,
        "shipping_template_id": 4024755547,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 199325709,
        "state": "active",
        "user_id": 9118393,
        "category_id": 69172099,
        "title": "Oz - 75 Years of Wickedness from Quilting Treasures - Wicked Witch and OZ on Black Quilt Fabric",
        "description": "This listing is for a full or half yard of a fantastic modern Wizard of Oz fabric line from Quilting Treasures.  Green wicked witches and gray Wizard of Oz writing on black.  \r\n\r\nHigh quality cotton fabric\r\n\r\n23377-j",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1407599754,
        "last_modified_tsz": 1422984667,
        "price": "5.45",
        "currency_code": "USD",
        "quantity": 8,
        "tags": ["modern oz", "oz 75 years of", "75 years wickedness", "quilting treasures", "wizard of oz fabric", "wicked witch fabric", "modern oz fabric"],
        "category_path": ["Supplies", "Fabric", "Cotton"],
        "category_path_ids": [69150433, 68888310, 69172099],
        "materials": [],
        "shop_section_id": 14197437,
        "featured_rank": null,
        "state_tsz": 1421976027,
        "url": "https:\/\/www.etsy.com\/listing\/199325709\/oz-75-years-of-wickedness-from-quilting?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 52,
        "num_favorers": 4,
        "shipping_template_id": 1232318828,
        "processing_min": 1,
        "processing_max": 3,
        "who_made": "someone_else",
        "is_supply": "true",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": ["Modern"],
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 186464437,
        "state": "active",
        "user_id": 40618568,
        "category_id": 69171715,
        "title": "Sheep Creek Agate Cabochon - Agate Cabochon - Lapidary Handmade Cabochon - Sheep Creek Agate",
        "description": "This lovely, tear-drop shaped, highly polished Sheep Creek Agate cabochon has a white tip, splashes of muted gold and brown throughout, and a scattering of black dendrites, all suspended in a translucent background. This attractive stone would look fantastic as the main focal piece in any jewelry setting. \r\n\r\n**********************************************************************\r\nDETAILS:\r\n\r\nSheeps Creek Agate Cabochon\r\n\r\n52 mm L x 18 mm W x 5 mm H approx.\r\n\r\n7 grams approx.\r\n\r\nBack is polished\r\n\r\nTop drilling not available\r\n\r\nPhotos are taken on a macro setting, in natural light, with no flash and enlarged to show details. Please see last picture for actual size reference (ruler is in millimeters).\r\n\r\n***********************************************************************\r\nDon&#39;t hesitate to convo me through Etsy if you have any questions about this cabochon or any other item in my shop.\r\n\r\nPlease read Shipping and Policies tab before making your purchase.\r\n\r\nAnd here&#39;s the link to my full selection of designer cabochons for sale:\r\nhttps:\/\/www.etsy.com\/ca\/shop\/SiO2Shop?section_id=14620673\r\n\r\nThanks for visiting!",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1397690884,
        "last_modified_tsz": 1422984667,
        "price": "18.00",
        "currency_code": "CAD",
        "quantity": "1",
        "tags": ["cabochon", "wire wrap", "wire wrap cab", "wire wrap cabochon", "gemstone", "designer cabochon", "lapidary cabochon", "jewelry supplies", "polished cab", "stone cabochon", "sio2shop", "agate cabochon", "sheeps creek agate"],
        "category_path": ["Supplies", "Handmade", "Cabochon"],
        "category_path_ids": [69150433, 69151267, 69171715],
        "materials": ["Sheeps Creek Agate", "C81"],
        "shop_section_id": 14620673,
        "featured_rank": null,
        "state_tsz": 1422927034,
        "url": "https:\/\/www.etsy.com\/listing\/186464437\/sheep-creek-agate-cabochon-agate?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 51,
        "num_favorers": 9,
        "shipping_template_id": 2630863712,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "true",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 205614621,
        "state": "active",
        "user_id": 10000670,
        "category_id": 69154969,
        "title": "Courage Doesn&#39;t Always Roar breast cancer awareness sign",
        "description": "In recognition of Breast Cancer Awareness month, a part of the proceeds from this piece will be donated to the American Cancer Society.  A simple message of strength and conviction.  The fight doesn&#39;t have to be loud, just strong.\r\n\r\nThis piece is light pink, black, and ivory.  Every item in my shop is made to order. Approximately 3 x 30&quot; sign. Each unique piece is hand cut, hand painted, and hand distressed. \r\n\r\nNot intended for outdoor use.\r\n\r\nAll designs and photos owned by Simply CHic Signs \u00a9 Copyright 2014-present. All Rights Reserved. Any and all infringements of the same shall be directed to legal counsel.",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1412212185,
        "last_modified_tsz": 1422984669,
        "price": "30.00",
        "currency_code": "USD",
        "quantity": 1,
        "tags": ["breast cancer", "pink ribbon", "donation", "inspirational", "motivational", "distressed", "courage", "over the door", "october", "quotation"],
        "category_path": ["Woodworking", "Sign"],
        "category_path_ids": [68887388, 69154969],
        "materials": ["acrylic paint", "pine board", "sawtooth hanger"],
        "shop_section_id": 16000902,
        "featured_rank": null,
        "state_tsz": 1422929433,
        "url": "https:\/\/www.etsy.com\/listing\/205614621\/courage-doesnt-always-roar-breast-cancer?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 21,
        "num_favorers": 0,
        "shipping_template_id": null,
        "processing_min": 5,
        "processing_max": 10,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": ["Cottage Chic", "Rustic"],
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 220585405,
        "state": "active",
        "user_id": 14187503,
        "category_id": 69169877,
        "title": "French Ribbon Bow (3 pc)",
        "description": "This classic bow has a wonderful drape and curve. Use two bows to frame a photo in a scrapbook. They can be gently bent to accessorize a show or tiara.\r\n\r\n1 3\/4&quot; wide x 3\/4&quot; tall, struck from light, yellow brass in America.",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1422572605,
        "last_modified_tsz": 1422984667,
        "price": "5.00",
        "currency_code": "USD",
        "quantity": 11,
        "tags": ["bow", "ribbon", "gift", "party", "favor", "frame", "design", "floral", "sachet", "sash", "dress", "drape", "french ribbon"],
        "category_path": ["Vintage", "Supplies", "Charm"],
        "category_path_ids": [69150437, 69153885, 69169877],
        "materials": ["brass", "copper", "metal", "yellow"],
        "shop_section_id": 14613651,
        "featured_rank": null,
        "state_tsz": 1422572605,
        "url": "https:\/\/www.etsy.com\/listing\/220585405\/french-ribbon-bow-3-pc?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 19,
        "num_favorers": 7,
        "shipping_template_id": null,
        "processing_min": null,
        "processing_max": null,
        "who_made": "someone_else",
        "is_supply": "true",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": ["Edwardian", "Victorian"],
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 207873861,
        "state": "active",
        "user_id": 32508243,
        "category_id": 69150467,
        "title": "U.S flag camera lens cap and leash combo for Canon, Nikon, Fuji, Sony etc. DSLR, mirrorless cameras. Free shipping in North America.",
        "description": "Quality custom lens caps and leashes from MyLensCap add style and flair to your camera.  This U.S flag lens cap\/leash design offers an attractive and practical accessory for your photography.\r\n\r\nWe use quality inks printed on durable vinyl, finished with a glossy laminate.  Images are permanently affixed to lens caps\/leashes designed to fit safely and securely to your camera.\r\n\r\n****NOTE: When attaching your leash to your lens cap be sure to get placement correct because once the sticky side is placed on the lens cap it is virtually impossible to pull it off.\r\n\r\nOrders are shipped out in 1-2 business days through the post office.\r\n\r\nNorth American orders typically will arrive within 3-14 business days.\r\n\r\nInternational orders typically will arrive within 2-6 weeks.",
        "creation_tsz": 1422984667,
        "ending_tsz": 1433349067,
        "original_creation_tsz": 1413828526,
        "last_modified_tsz": 1422984667,
        "price": "16.99",
        "currency_code": "CAD",
        "quantity": "1",
        "tags": ["camera strap", "photo accessory", "dslr camera", "photography gift", "personalized cap", "strap cover", "camera case", "custom lens caps", "lens cap holder", "lens cover", "photographer print", "lens cap leash"],
        "category_path": ["Accessories"],
        "category_path_ids": [69150467],
        "materials": [],
        "shop_section_id": 16200010,
        "featured_rank": null,
        "state_tsz": 1413828526,
        "url": "https:\/\/www.etsy.com\/listing\/207873861\/us-flag-camera-lens-cap-and-leash-combo?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 4,
        "num_favorers": 0,
        "shipping_template_id": 4024755547,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 165272813,
        "state": "active",
        "user_id": 6852572,
        "category_id": 69188743,
        "title": "Bucket Bag Purse \/\/ Saddle Brown Leather Purse by Fullgive",
        "description": "BUCKET BAG. Perfectly sized purse for life on the go. Handmade from beautifully tanned leather, which only gets better with age. Zip pocket for essentials. Measures 9x11x3 inches.",
        "creation_tsz": 1422984666,
        "ending_tsz": 1433349066,
        "original_creation_tsz": 1381344884,
        "last_modified_tsz": 1422984666,
        "price": "199.00",
        "currency_code": "USD",
        "quantity": "1",
        "tags": ["bucket bag", "purse", "leather purse", "Saddle", "tan leather", "brown leather bag", "clutch", "new item", "christmas", "soft leather", "leather bag", "cross body bag", "hand bag"],
        "category_path": ["Bags and Purses", "Purse", "Leather"],
        "category_path_ids": [69150455, 69151533, 69188743],
        "materials": ["leather"],
        "shop_section_id": 10645505,
        "featured_rank": null,
        "state_tsz": 1421356076,
        "url": "https:\/\/www.etsy.com\/listing\/165272813\/bucket-bag-purse-saddle-brown-leather?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 5361,
        "num_favorers": 667,
        "shipping_template_id": null,
        "processing_min": 3,
        "processing_max": 5,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": "women",
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }, {
        "listing_id": 207878253,
        "state": "active",
        "user_id": 32508243,
        "category_id": 69150467,
        "title": "Ladybug camera lens cap, lens cap leash and linen photo accessories bag for Canon, Nikon, Fuji etc. Free shipping in North America.",
        "description": "Quality custom lens caps, leashes and linen bags from MyLensCap add style and flair to your camera.  This ladybug lens cap\/leash\/linen bag design offers an attractive and practical accessory for your photography.\r\n\r\nWe use quality inks printed on durable vinyl, finished with a glossy laminate.  Images are permanently affixed to lens caps\/leashes designed to fit safely and securely to your camera.\r\n\r\nLinen bag images are quality printed transfers set using a digital heat press.\r\n\r\n****NOTE: When attaching your leash to your lens cap be sure to get placement correct because once the sticky side is placed on the lens cap it is virtually impossible to pull it off.\r\n\r\nOrders are shipped out in 1-2 business days through the post office.\r\n\r\nNorth American orders typically will arrive within 3-14 business days.\r\n\r\nInternational orders typically will arrive within 2-6 weeks.",
        "creation_tsz": 1422984665,
        "ending_tsz": 1433349065,
        "original_creation_tsz": 1413830487,
        "last_modified_tsz": 1422984665,
        "price": "19.99",
        "currency_code": "CAD",
        "quantity": "1",
        "tags": ["camera strap", "photo accessory", "dslr camera", "photography gift", "personalized cap", "strap cover", "camera case", "custom lens caps", "lens cap holder", "lens cover", "photographer print", "lens cap leash", "linen bag"],
        "category_path": ["Accessories"],
        "category_path_ids": [69150467],
        "materials": [],
        "shop_section_id": 16199011,
        "featured_rank": null,
        "state_tsz": 1413830487,
        "url": "https:\/\/www.etsy.com\/listing\/207878253\/ladybug-camera-lens-cap-lens-cap-leash?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 18,
        "num_favorers": 3,
        "shipping_template_id": 4024755547,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 207878637,
        "state": "active",
        "user_id": 32508243,
        "category_id": 69150467,
        "title": "Shamrock camera lens cap, lens cap leash and linen photo accessories bag for Canon, Nikon, Fuji etc. Free shipping in North America.",
        "description": "Quality custom lens caps, leashes and linen bags from MyLensCap add style and flair to your camera.  This Shamrock lens cap\/leash\/linen bag design offers an attractive and practical accessory for your photography.\r\n\r\nWe use quality inks printed on durable vinyl, finished with a glossy laminate.  Images are permanently affixed to lens caps\/leashes designed to fit safely and securely to your camera.\r\n\r\nLinen bag images are quality printed transfers set using a digital heat press.\r\n\r\n****NOTE: When attaching your leash to your lens cap be sure to get placement correct because once the sticky side is placed on the lens cap it is virtually impossible to pull it off.\r\n\r\nOrders are shipped out in 1-2 business days through the post office.\r\n\r\nNorth American orders typically will arrive within 3-14 business days.\r\n\r\nInternational orders typically will arrive within 2-6 weeks.",
        "creation_tsz": 1422984665,
        "ending_tsz": 1433349065,
        "original_creation_tsz": 1413830642,
        "last_modified_tsz": 1422984665,
        "price": "19.99",
        "currency_code": "CAD",
        "quantity": "1",
        "tags": ["camera strap", "photo accessory", "dslr camera", "photography gift", "personalized cap", "strap cover", "camera case", "custom lens caps", "lens cap holder", "lens cover", "photographer print", "lens cap leash", "linen bag"],
        "category_path": ["Accessories"],
        "category_path_ids": [69150467],
        "materials": [],
        "shop_section_id": 16199011,
        "featured_rank": null,
        "state_tsz": 1413830642,
        "url": "https:\/\/www.etsy.com\/listing\/207878637\/shamrock-camera-lens-cap-lens-cap-leash?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 30,
        "num_favorers": 2,
        "shipping_template_id": 4024755547,
        "processing_min": 1,
        "processing_max": 2,
        "who_made": "i_did",
        "is_supply": "false",
        "when_made": "made_to_order",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": null,
        "non_taxable": false,
        "is_customizable": true,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": true,
        "used_manufacturer": false
    }, {
        "listing_id": 199940493,
        "state": "active",
        "user_id": 9291716,
        "category_id": 69160197,
        "title": "Wrench ring instainless steel",
        "description": "wrench ring...7\/8&quot; wide at the widest spot on top, cast in stainless steel....I had these made 6 or 7 years ago, never listed them because they have been copied many times...I have them in size 7,8,9,10,11 and 12 also in shiny and satin finish ( see last photo)...when you order please put the ring size you want and shiny or satin in the notes...special price $15.00",
        "creation_tsz": 1422984663,
        "ending_tsz": 1433349063,
        "original_creation_tsz": 1408048236,
        "last_modified_tsz": 1422984663,
        "price": "13.00",
        "currency_code": "USD",
        "quantity": 2,
        "tags": ["wrench ring", "wrench", "Von Dutch", "western", "low brow", "tattoo", "outlaw", "biker", "car guy", "cars"],
        "category_path": ["Jewelry", "Ring", "Metalwork"],
        "category_path_ids": [68887482, 69152047, 69160197],
        "materials": [],
        "shop_section_id": 8150606,
        "featured_rank": null,
        "state_tsz": 1415593353,
        "url": "https:\/\/www.etsy.com\/listing\/199940493\/wrench-ring-instainless-steel?utm_source=etsyproject&utm_medium=api&utm_campaign=api",
        "views": 345,
        "num_favorers": 43,
        "shipping_template_id": 17476192,
        "processing_min": null,
        "processing_max": null,
        "who_made": "collective",
        "is_supply": "false",
        "when_made": "2010_2015",
        "is_private": false,
        "recipient": null,
        "occasion": null,
        "style": ["Boho", "Avant Garde"],
        "non_taxable": false,
        "is_customizable": false,
        "is_digital": false,
        "file_data": "",
        "language": "en-US",
        "has_variations": false,
        "used_manufacturer": false
    }],
    "params": {
        "limit": 25,
        "offset": 0,
        "page": null,
        "keywords": null,
        "sort_on": "created",
        "sort_order": "down",
        "min_price": null,
        "max_price": null,
        "color": null,
        "color_accuracy": 0,
        "tags": null,
        "category": null,
        "location": null,
        "lat": null,
        "lon": null,
        "region": null,
        "geo_level": "city",
        "accepts_gift_cards": "false",
        "translate_keywords": "false"
    },
    "type": "Listing",
    "pagination": {
        "effective_limit": 25,
        "effective_offset": 0,
        "next_offset": 25,
        "effective_page": 1,
        "next_page": 2
    },
    "ok": true
});
